name: TB Reusable Callers

on:
  push:
    branches:
      - main
      - "tb-lowtrust-*"

jobs:
  caller_without_id_token:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/tb-reusable-callee.yml
    with:
      scenario: reusable-caller-without-id-token

  caller_with_id_token:
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/tb-reusable-callee.yml
    with:
      scenario: reusable-caller-with-id-token

